import React,{useState} from 'react';
import Field from './Field';
import {api,money} from '../lib/api';
export default function Management({tab,data,act,busy}){
 const [edit,setEdit]=useState(null);
 return <><button className="button" onClick={()=>setEdit(tab==='services'?{name:'',description:'',price:55,duration:45,active:1}:{name:'',specialty:'',photo:'',rating:5,active:1})}>+ Adicionar {tab==='services'?'serviço':'barbeiro'}</button><div className="grid manage">{data[tab].map(item=><article key={item.id}><h3>{item.name}</h3><p>{item.description||item.specialty}</p><small>{tab==='services'?`${money(item.price)} · ${item.duration} min`:`★ ${item.rating}`} · {item.active?'Ativo':'Inativo'}</small><div className="actions"><button onClick={()=>setEdit(item)}>Editar</button><button disabled={busy} onClick={()=>act(()=>api(`/admin/${tab}/${item.id}`,undefined,'DELETE'))}>Excluir / desativar</button></div></article>)}</div><p className="muted">Registros com histórico são desativados para preservar as reservas.</p>
 {edit&&<form className="editor" onSubmit={e=>{e.preventDefault();act(async()=>{await api(`/admin/${tab}${edit.id?'/'+edit.id:''}`,edit,edit.id?'PUT':'POST');setEdit(null);});}}><h3>{edit.id?'Editar':'Novo'} {tab==='services'?'serviço':'barbeiro'}</h3><Field label="Nome" required minLength={2} maxLength={80} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/>
 {tab==='services'?<><Field label="Descrição" maxLength={300} value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/><div className="two"><Field label="Preço (R$)" type="number" min="0" max="10000" step="0.01" required value={edit.price} onChange={e=>setEdit({...edit,price:e.target.value})}/><Field label="Duração (minutos)" type="number" min="15" max="240" required value={edit.duration} onChange={e=>setEdit({...edit,duration:e.target.value})}/></div></>:<><Field label="Especialidade" maxLength={150} value={edit.specialty} onChange={e=>setEdit({...edit,specialty:e.target.value})}/><Field label="Foto (URL HTTPS, opcional)" type="url" value={edit.photo} onChange={e=>setEdit({...edit,photo:e.target.value})}/><Field label="Avaliação (0–5)" type="number" min="0" max="5" step="0.1" required value={edit.rating} onChange={e=>setEdit({...edit,rating:e.target.value})}/></>}
 <label className="field">Disponibilidade<select value={edit.active} onChange={e=>setEdit({...edit,active:Number(e.target.value)})}><option value="1">Ativo</option><option value="0">Inativo</option></select></label><button className="button" disabled={busy}>Salvar</button><button type="button" onClick={()=>setEdit(null)}>Fechar</button></form>}</>;
}
